[build]
  base = "stemuplift.org"
  publish = "public"
  command = "./build.sh"

[context.production.environment]
# I'm fixing Hugo version to make sure my theme doesn't break
HUGO_VERSION = "0.47.1"
HUGO_ENV = "production"
